### ISSUE TITLE
Suggestion for OCI: Consolidated Document

### ISSUE THREAD

**Issue by vsoch** [supercontainers/containers-wg#9]
From the slack, it would be useful if the specs could be published in a more holistic documen, akin to an RFC. Even a nice web interface in some clean format would work! From @reidpr :

> I’d love consolidation of the standard into a single coherent document, e.g. RFC style.

**Comment by btklein** [comment]
Worth mentioning in today's meeting?  Perhaps the effort to document RFC style would be an appropriate motion to create an OCI working group

**Comment by vsoch** [comment]
Sure thing! I would definitely be down to work on this.

**Comment by btklein** [comment]
Ditto.  Perhaps we mention it today, but create a pull request in https://github.com/opencontainers/artifacts

**Comment by vsoch** [comment]
I was able to mention it right at the end, because a place to put common documents/projects was referenced. I've never created an RFC document before (are there templates out there?), but I think it would be worth looking into, and then seeing how the current specs are published (if at all). A very simple design could be to have an RFC jekyll template that can grab the current versions of the specs, and also allow adding extra content (e.g., comments, new working groups, etc.) What do you think?

**Comment by btklein** [comment]
Yes, you were able to get the question in perfectly at the end!  Interestingly enough, it was fantastic how the topic of working groups was naturally brought up outside of our original intention as well! Great job and thanks for sneaking it in at the end

**Comment by vsoch** [comment]
To update the discussion here, over the weekend I made (and [wrote about](https://vsoch.github.io/2021/rfc-jekyll/)) https://vsoch.github.io/rfc-jekyll/runtime-spec/

**Comment by vsoch** [comment]
Stick a fork in me... https://specs.opencontainers.org/ done! :partying_face:
